### ISSUE TITLE
no package.json file 

### ISSUE THREAD

**Issue by drascom** [khoaang/doorlock#1]
i am getting error for npm install you didnt upload package.json file to main folder it is inside frontend folder 
ENOENT: no such file or directory, open '/test/doorlock/package.json'
```
cd frontend
npm install
```
 works

**Comment by khoaang** [comment]
Thank you for bringing this to our attention. The structure of our project separates the front-end and back-end concerns into their own respective directories for clarity and separation of concerns. The package.json file resides within the frontend folder because it specifically manages the JavaScript dependencies for the front-end part of our application, which is built with a JavaScript framework or library.

For the back-end, we are using Python Flask, which does not require a package.json. Instead, Flask dependencies are managed by a requirements.txt file,
